version: '3.8'
services:
  q-nav:
    image: qninq/q-nav:latest
    container_name: q-nav
    ports:
      - "3003:3003"
    restart: unless-stopped
    volumes:
      - ./data.json:/data.json
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3003"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
